import { Light, LightingPreset } from '@/types';

export const lightingPresets: Record<LightingPreset, Light[]> = {
  'three-point': [
    {
      id: 'key-light',
      type: 'directional',
      intensity: 1.5,
      color: '#ffffff',
      position: [5, 5, 5],
      enabled: true,
    },
    {
      id: 'fill-light',
      type: 'directional',
      intensity: 0.5,
      color: '#ffffff',
      position: [-3, 2, 3],
      enabled: true,
    },
    {
      id: 'back-light',
      type: 'directional',
      intensity: 0.8,
      color: '#ffffff',
      position: [0, 3, -5],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.3,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'high-key': [
    {
      id: 'main-light',
      type: 'directional',
      intensity: 1.2,
      color: '#ffffff',
      position: [3, 5, 3],
      enabled: true,
    },
    {
      id: 'fill-1',
      type: 'directional',
      intensity: 0.8,
      color: '#ffffff',
      position: [-3, 3, 3],
      enabled: true,
    },
    {
      id: 'fill-2',
      type: 'directional',
      intensity: 0.6,
      color: '#ffffff',
      position: [0, 2, -3],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.7,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'low-key': [
    {
      id: 'key-light',
      type: 'directional',
      intensity: 2,
      color: '#ffffff',
      position: [5, 3, 2],
      enabled: true,
    },
    {
      id: 'rim-light',
      type: 'directional',
      intensity: 0.5,
      color: '#4488ff',
      position: [-2, 2, -5],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.1,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'soft': [
    {
      id: 'soft-top',
      type: 'directional',
      intensity: 0.7,
      color: '#ffffff',
      position: [0, 5, 0],
      enabled: true,
    },
    {
      id: 'soft-front',
      type: 'directional',
      intensity: 0.6,
      color: '#ffffff',
      position: [0, 3, 5],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.6,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'hard': [
    {
      id: 'hard-main',
      type: 'directional',
      intensity: 2.5,
      color: '#ffffff',
      position: [5, 5, 3],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.2,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'backlighting': [
    {
      id: 'back-main',
      type: 'directional',
      intensity: 2,
      color: '#ffffff',
      position: [0, 3, -8],
      enabled: true,
    },
    {
      id: 'rim-left',
      type: 'directional',
      intensity: 1,
      color: '#ffffff',
      position: [-5, 2, -5],
      enabled: true,
    },
    {
      id: 'rim-right',
      type: 'directional',
      intensity: 1,
      color: '#ffffff',
      position: [5, 2, -5],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.2,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'side-lighting': [
    {
      id: 'side-main',
      type: 'directional',
      intensity: 1.8,
      color: '#ffffff',
      position: [8, 3, 0],
      enabled: true,
    },
    {
      id: 'opposite-fill',
      type: 'directional',
      intensity: 0.3,
      color: '#ffffff',
      position: [-3, 2, 0],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.3,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'frontal': [
    {
      id: 'frontal-main',
      type: 'directional',
      intensity: 1.5,
      color: '#ffffff',
      position: [0, 2, 8],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.5,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'underlighting': [
    {
      id: 'under-main',
      type: 'directional',
      intensity: 2,
      color: '#ff6666',
      position: [0, -5, 3],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.1,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'top-lighting': [
    {
      id: 'top-main',
      type: 'directional',
      intensity: 2,
      color: '#ffffff',
      position: [0, 10, 0],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.2,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'silhouette': [
    {
      id: 'silhouette-back',
      type: 'directional',
      intensity: 3,
      color: '#ffffff',
      position: [0, 0, -10],
      enabled: true,
    },
    {
      id: 'ambient',
      type: 'ambient',
      intensity: 0.05,
      color: '#ffffff',
      position: [0, 0, 0],
      enabled: true,
    },
  ],
  'custom': [],
};

export const presetDescriptions: Record<LightingPreset, string> = {
  'three-point': 'Classic setup with key, fill, and back lights',
  'high-key': 'Bright, evenly lit with minimal shadows',
  'low-key': 'Dramatic contrast with strong shadows',
  'soft': 'Diffused, gentle lighting',
  'hard': 'Sharp shadows and high contrast',
  'backlighting': 'Halo effect with rim separation',
  'side-lighting': 'Emphasizes texture and form',
  'frontal': 'Flat, even lighting from front',
  'underlighting': 'Horror/dramatic effect from below',
  'top-lighting': 'Powerful spotlight from above',
  'silhouette': 'Strong backlight only',
  'custom': 'Create your own lighting setup',
};
